bytedance/xgplayer

README.md, README.zh-CN.md, package.json
Babel-cli must be installed globally before executing npm run dev
=> fix: babel-node: command not found

packages/xgplayer/webpack.config.test.js
executing ```npm run test``` on packagses/xgplayer will get an error.
```
ERROR in chunk test/player.spec [entry]
index.js
Conflict: Multiple chunks emit assets to the same filename index.js (chunks main and test/player.spec)
ERROR in chunk test/utils/util.spec [entry]
index.js
Conflict: Multiple chunks emit assets to the same filename index.js (chunks main and test/utils/util.spec)
```
Maybe we need make output dynamic,Then we can run the unit test normally.
=> fix: Multiple assets emit to the same filename

packages/xgplayer/src/proxy.js
- play and pause methods return a promise which is useful. it is better to expose them to user.
- canPlayType needs parameters
- currentSrc is readonly property which cannot be modified
=> fix(xgplayer): fix play() pause() canPlayType() and currentSrc

packages/xgplayer/src/control/progress.js
=> fix: 进度条控件中的开闭标签不一致

packages/xgplayer/src/player.js
西瓜播放器在 destroy 后可能会触发 ready 事件，导致一些报错。（比如在 ready 里面会调用 player.controls.appendChild，但是 player.controls 在 destroy 时已经被删除了）
=> fix: cleanup all listeners when destroy

yarn.lock
accroding to https://github.com/bytedance/xgplayer/pull/922, `yarn.lock` file was changed and some package was described to bnpm registry.
=> 调整原本安装在bnpm的包的registry

packages/xgplayer-flv/src/flv/services/buffer-service.js, packages/xgplayer-hls/src/hls/buffer-service/index.js, packages/xgplayer-hls/src/hls/buffer-service/transmuxer/index.js, packages/xgplayer-hls/src/hls/index.js, packages/xgplayer-hls/src/hls/manifest-loader/parser/media.js, packages/xgplayer-hls/src/plugin.js, packages/xgplayer-streaming-shared/src/event.js, packages/xgplayer-streaming-shared/src/services/stats.js, packages/xgplayer-transmuxer/src/flv/fixer.js
fix: (xgplayer-hls) 过滤duration为0的分片
fix: (xgplayer-hls) beforePlayerInit()钩子去除异步返回值
fix: (xgplayer-flv) audio timestamp breaked before video long time case play stall
refact: core.demuxedtrack export demuxed video & audio track
=> hls & flv fix

packages/xgplayer/src/plugins/pip/index.js
切换PIP状态 调用方法 switchPIP 报错 e.stopPropagation not a function
=> fix: 调用 switchPIP 报错 e.stopPropagation not a function

packages/xgplayer/src/plugins/pc/index.js
单击和双击事件共享了 _clickCount 状态，这样设计有什么考虑吗？ @hongqx
=> fix: 🐛 (player) 修复closeVideoClick=true时，双击事件无效问题 (fixed #970)

packages/xgplayer/src/plugins/track/index.js
修复以下方法调用不能更新字幕
```
ttPlugin.updateSubtitles([
{
id: "srt1",
url: URL.createObjectURL(val),
language: "zh-cn",
text: "字幕1",
default: true,
},
])
```
=> fix: (xgplayer-texttrack) 修复updateSubtitles不能更新字幕

packages/xgplayer-music/src/plugins/musicBackward.js
It‘s invalid to add 'musicbackward' in 'ignores'
=> fix(xgplayer-music):fix typos

packages/xgplayer/src/plugins/progress/index.js
修复问题：autoplay未设置时，视频手动seek后，如果调用playNext切换视频，progress和time两个插件的状态都重置，但progress的按钮位置未重置。
=> fix(xgplayer): reset progress btn position when playnext

packages/xgplayer-transmuxer/__tests__/codec/nalu.spec.js, packages/xgplayer-transmuxer/src/codec/nalu.js
This is a re-submission of the pull request #1238
=> Remove RBSP trailing bits when parsing SEI

packages/xgplayer-hls/src/hls/playlist/stream.js
当播放为直播模式，且首个m3u8返回的可播放ts个数为一个且sn标志置为0时，ts的加载会在后续m3u8轮询到足够的ts文件个数后再开始加载，过程中segments的更新会因为sn错误的取到-1而导致更新错误，从而多次请求首个ts文件
=> fix(xgplayer-hls): sn 为 0时会错误取到-1

packages/xgplayer-hls/src/hls/index.js
测试视频：https://voddemo-play.volcvod.com/8c4a89ef7cb646429c48f7d0fa21bd38/main.m3u8?auth_key=1794666117-338fee8476374722991d5abdc974979b-0-2077017041f0814607fcb26c35d9dcee
=> fix: 🐛 (xgplayer-hls）修复hls最后一个切片不渲染，并且播放到最后一直loading的问题

packages/xgplayer/src/utils/sniffer.js
=> chore: remove duplicate codec item for MP4 support check

fixtures/xgplayer/index.js, packages/xgplayer/src/plugins/pip/index.js
修复画中画插件 isPIPAvailable 的判断逻辑，document.pictureInPictureEnabled 不存在时则表示不支持，见[w3c pip](https://www.w3.org/TR/picture-in-picture/#examples)，可在不支持画中画的firefox上验证
=> fix(xgplayer): pip available

fixtures/mp4/index.html, packages/xgplayer-mp4/src/mp4.js, packages/xgplayer-mp4/src/mp4Plugin.js
支持苹果ios 17引入的MMS
fix issue #1578 
使MP4插件支持苹果ios17 的MMS。
默认关闭 需要在配置中打开：
```javascript
{
plugins: [Mp4Plugin],
// set mp4Plugin support Apple's MMS
mp4Plugin: {
preferMMS: true
}
} 
```
=> Fix mp4  MMS support 支持苹果的MMS

packages/xgplayer/src/index.js, scripts/commands/build/index.js
在使用 xgplayer 播放器的过程按照官方描述引入多语言文件时发现 es/lang 包内并没有 ru 等语言文件
目录内只有 ru.d.ts 文件并没有 ru.js 文件
在打包时拷贝 `packages/xgplayer/src/lang` 到 `packages/xgplayer/es/lang` 中
这样虽然解决了问题，但我无法确定是否是正确的！
=> fix: (xgplayer) 修复打包后 es / lang 文件夹多语言文件缺失的问题

packages/xgplayer-transmuxer/src/codec/aac.js
解决部分Chrome下不支持22050Hz 没有设置extensionSampling导致解码失败的问题
=> fix: 调整chrome下acc默认objectType

packages/xgplayer-dash/src/dash.js
`getData` 方法中未声明变量 `self`，导致代码引用不存在的 `self` 时出现问题。由于此处使用箭头函数，因此可改为使用 `this` ，确保 DASH 实例能够正常处理错误。
=> fix: fix the issue of the undefined self variable in the getData method.

packages/xgplayer/src/lang/zh-hk.js
暂不讨论港澳台及新加坡的书面语言和技术名词差异。
在流媒体领域，「劉」这个字不会被使用。
「劉」在华人社群中通常是姓氏，在这里明显是笔误，因此进行了修正。
=> fix(lang): fix typo in zh-hk

packages/xgplayer/src/player.js
fix: #1766 
多做了一层兼容处理，减少不必要的线上报错。
=> fix: null is not an object (evaluating 'this.root.getBoundingClientRect')

packages/xgplayer-ads/src/ui/adUIManager.js, packages/xgplayer-subtitles/src/parser.js, packages/xgplayer/src/player.js, packages/xgplayer/src/plugin/plugin.js, packages/xgplayer/src/plugins/miniScreen/index.js, packages/xgplayer/src/plugins/time/index.js
- 修复在手机屏幕已横置状态下，调用css旋转全屏，其播放器尺寸计算错误不能占满全屏的问题
- vtt格式字幕文件的识别兼容非大写的内容
-  修复ad插件timeIcon，在control栏的mode是flex时，其time的dom无法正确显示隐藏的问题
=> 修复css旋转全屏尺寸计算错误 & ad插件timeIcon显隐问题

packages/xgplayer-hls.js/src/index.js
`hasVideo` 变量的判断条件，之前是基于 `payload.tracks.audio`，但根据代码上下文，应该改为使用 `payload.tracks.video` 进行判断。
=> fix: assign hasVideo based on video track

packages/xgplayer/src/plugin/hooksDescriptor.js
修复 [官方文档 - 内置插件 - progress - 限制用户只能在播放过的位置进行seek](https://h5player.bytedance.com/plugins/internalplugins/progress.html#%E9%99%90%E5%88%B6%E7%94%A8%E6%88%B7%E5%8F%AA%E8%83%BD%E5%9C%A8%E6%92%AD%E6%94%BE%E8%BF%87%E7%9A%84%E4%BD%8D%E7%BD%AE%E8%BF%9B%E8%A1%8Cseek-%E5%8D%B3%E5%90%91%E5%89%8Dseek) 无法正常使用的问题。
在此 pr 合并之前，可以通过以下补丁临时修复此功能。
包管理工具：pnpm
播放器版本：v3.0.23-rc.2
补丁包：[xgplayer@3.0.23-rc.2.patch](https://github.com/user-attachments/files/20684168/xgplayer%403.0.23-rc.2.patch)
#1401 
#1668 
#1685 
#1692 
#1773 
#1730
=> fix: 修复因返回值问题，导致 “限制用户向前seek” 示例无效的问题

packages/xgplayer-mp4/src/mp4.js
fix https://github.com/bytedance/xgplayer/issues/1432
[test mp4 file without audio track](https://github.com/user-attachments/assets/15825520-5426-4d80-bebf-d5bc67e9fb41)
=> mp4 plugin fix: check if video/audio track has segments before accessing
