bytedance/xgplayer

packages/xgplayer-mp4/src/util/index.js
packages/xgplayer-mp4/test/util.spec.js

- add test for  findbox function
- update findbox function descript

add test for findbox

---

packages/xgplayer/src/control/error.js

fix: player多次error时会多次添加刷新按钮的点击事件监听

---

packages/xgplayer-render-filter-kernel/browser/index.js
packages/xgplayer-render-filter-kernel/dist/index.js
packages/xgplayer-render-filter-kernel/package.json
packages/xgplayer-render-filter-kernel/rollup.config.js
packages/xgplayer-render-filter-kernel/src/Template.js
packages/xgplayer-render-filter-kernel/src/index.js

fixed package

---

packages/xgplayer/src/control/progress.js

可批量增加progress dot，使用方法
```javascript
player.addProgressDots([
{
time: 2,
text: 'haha',
duration: 2,
},
{
time: 10,
text: 'sdfsdfsd',
duration: 4,
},
])
```

[feat]增加addProgressDots方法

---

packages/xgplayer/src/control/mobile.js
packages/xgplayer/src/player.js
packages/xgplayer/src/skin/controls/start.js

1.modify the timing of className xgplayer-is-enter at root;    
2.the compatibility problem that waiting not trigger in IE;
3.the poster can`t show in safari when the autoplay was prevented because of Playing was triggeredC

fix: 1.modify the timing of className xgplayer-is-enter at root;

---

packages/xgplayer-render/src/fmt/nv12.js

reset viewport in N12 filter

---

packages/xgplayer-dash/package.json
packages/xgplayer-flv.js/package.json
packages/xgplayer-flv/package.json
packages/xgplayer-hls.js/package.json
packages/xgplayer-hls/package.json
packages/xgplayer-m4a/package.json
packages/xgplayer-mp4/package.json
packages/xgplayer-music/package.json
packages/xgplayer-shaka/package.json

fix: peerDep field and version

---

.github/ISSUE_TEMPLATE/-----bug-report.md
packages/xgplayer/README.md

update  `What version of xglayer are you using`  to `What version of xgplayer are you using`

docs: update bug template version description

---

packages/xgplayer-mp4-loader/package.json
packages/xgplayer-transmuxer/package.json
yarn.lock

xgplayer-transmuxer@3.0.2 merge into main

update xgplayer-transmuxer and loader package.json

---

.github/workflows/publish.yml
package.json
packages/xgplayer-mp4-new/package.json
scripts/commands/build/index.js
scripts/context.js
scripts/utils/index.js
scripts/workflow/block-list.mjs
scripts/workflow/npm-publish.mjs
scripts/workflow/set-package-version.mjs
yarn.lock

完善发布脚本，可以更新每个包的peerDeps和deps

---

packages/xgplayer-flv/src/flv/services/buffer-service.js

fix: (xgplayer-flv) play error with only script tag received first fetch chunk

---

packages/xgplayer/src/plugins/fpsDetect/index.js

add parmas when report fps stuck

feat(xgplayer): report fps stuck

---

packages/xgplayer-hls/CHANGELOG.md
packages/xgplayer-hls/src/hls/buffer-service/index.js
packages/xgplayer-hls/src/hls/config.js
packages/xgplayer-hls/src/hls/index.js
packages/xgplayer-streaming-shared/src/buffer.js

fix: 分片时长与m3u8中指定不一致漏下载分片case
feat: setInTime 默认不开启

fix: (xgplayer-hls)

---

packages/xgplayer/src/plugins/testspeed/index.js

testSpeed support other type test

---

packages/xgplayer/src/plugins/testspeed/index.js

修复speedListCache type不存在时候访问的报错

fix speedListCache null error

---

packages/xgplayer/src/defaultConfig.js
packages/xgplayer/src/player.js
packages/xgplayer/src/plugins/time/index.js
packages/xgplayer/src/plugins/time/index.scss
packages/xgplayer/src/style/common.scss
scripts/commands/build/index.js
scripts/context.js
scripts/utils/index.js
scripts/workflow/create-release-pr.js

在视频播放过程中，当前时间(`hh:mm:ss/hh:mm:ss`或`mm:ss/mm:ss`)不停地抖动，影响用户体验。这个PR通过设置`hh`, `mm`, `ss`的`min-width: 2ch`优化这个问题。关于`ch`请参考[MDN](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units).
> `ch`: The advance measure (width) of the glyph "0" of the element's font.

fix: current time shifting when updating

---

fixtures/xgplayer/index.js
packages/xgplayer/package.json
packages/xgplayer/src/player.js
packages/xgplayer/src/plugins/keyboard/index.js
packages/xgplayer/src/plugins/progress/index.js
packages/xgplayer/src/plugins/progressPreview/index.js
packages/xgplayer/src/plugins/time/index.js
packages/xgplayer/src/plugins/time/timesegments.js
packages/xgplayer/src/presets/default.js
packages/xgplayer/src/utils/util.js

feat(xgplayer): 增加TimeSegmentsControls插件
feat(xgplayer): 快捷键seek添加分段时长偏移量

feat(xgplayer): 添加timeSegments配置,支持分段时长合并播放能力

---

packages/xgplayer/src/plugins/screenShot/index.js

feat: 截图增加同v2版本saveImg字段，控制截图下载保存

---

packages/xgplayer-transmuxer/src/mp4/mp4-parser.js

For consumption purpose like WebCodec description

align with hvcC structure adding raw binary data to box info of avcC

---

fixtures/hls/index.js
packages/xgplayer-hls/src/plugin.js

HLS插件的switchURL方法添加返回Promise，保持与主包的switchURL方法一致特性

fix(xgplayer-hls): hls plugin switchURL api add Promise return

---

packages/xgplayer-flv/src/flv/index.js
packages/xgplayer-hls/CHANGELOG.md
packages/xgplayer-hls/src/hls/buffer-service/index.js
packages/xgplayer-hls/src/plugin.js
packages/xgplayer-streaming-shared/src/event.js

feat: (xgplayer-hls) add core.mediasourceopended event

fix: (xgplayer-flv) safari firstframe stall

---

packages/xgplayer-flv/src/flv/index.js
packages/xgplayer-flv/src/flv/options.js
packages/xgplayer-streaming-shared/src/services/bandwidth.js
packages/xgplayer-streaming-shared/src/services/stats.js

feat: (xgplayer-flv) export configuration for speed evaluate
fix: (xgplayer-flv) seamless switch error case canplay、playing event emit again
feat: (xgplayer-flv) export totalSize、 totalCost for speedInfo()

feat: (xgplayer-flv) update download speed evaluate strategy

---

packages/xgplayer/src/player.js

修复安卓hls原生播放，startTime不生效的问题。抽取跳转配置的起播时间的公共逻辑

fix(xgplayer): android hls origin video play's startTime

---

packages/xgplayer-transmuxer/src/codec/mpeg.js
packages/xgplayer-transmuxer/src/mpeg-ts/index.js

fix: mp3音频没声音

---

.github/workflows/publish.yml

Added the permission of git commit and PR creation.

Update publish.yml for default permission change
